### PR TITLE
Webpack module rule regex updated for .postcss and .pcss file ext

### PR DESCRIPTION
**Pull request by Asim-Tahir**
Added optional .postcss and .pcss file extension regex. It's still support .css file extension.

### CODE REVIEW

**Comment by phated** [comment]
I've not seen this as a common pattern/file extension. Do you have a link to this recommendation?

**Comment by Asim-Tahir** [comment]
I first seen .pcss and .postcss file ext in [here](https://marketplace.visualstudio.com/items?itemName=csstools.postcss)

**Comment by Asim-Tahir** [comment]
Any updated 👀

**Comment by Asim-Tahir** [comment]
@knightly-bot build this

**Comment by antfu** [comment]
@knightly-bot build this

**Comment by Asim-Tahir** [comment]
@knightly-bot build this

**Comment by zakkor** [comment]
We need this too, or at least an option to make it configurable.

**Comment by RumyantsevMichael** [comment]
I believe you should support .pcss as it is widely used.
For instance, webstorm supports this extension out of the box (https://plugins.jetbrains.com/plugin/8578-postcss)

**Comment by fvanwijk** [comment]
.postcss extension needs to be matched for .vue files that have `<style lang="postcss">`

**Comment by alkorlos** [comment]
@phated Yes, official twitter PostCSS recommendation use .pcss extension for PostCSS based sources.

**Pull request closed without merging**
